.Dd 5/14/11
.Dt askpass 1
.Os Darwin
.Sh NAME
.Nm askpass
.Nd grapical password prompter
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
displays a password prompt in a graphical dialog, and emits the entered password
to standard out.
.Pp
It is suitable for use by
.Ar sudo
as a
.Ar SUDO_ASKPASS
helper.
.Sh SEE ALSO 
.Xr sudo 8
.\" .Sh BUGS
.\" .Sh HISTORY
.Sh AUTHOR
.An "Greg Hurrell"
\[la]greg@hurrell.net\[ra]
.Sh WEBSITE
.Ad https://wincent.dev/products/askpass
.Sh LICENSE
Copyright 2011-present Greg Hurrell. All rights reserved.
.Pp
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
.Pp
1. Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
.Pp
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
.Pp
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
